CREATE TABLE TB_CADASTRO 
(
  CD_AGENCIA    VARCHAR(3)   NOT NULL,
  NR_CONTA      VARCHAR(60)  NOT NULL,
  TITULARIDADE  CHAR(1),
  CPF           VARCHAR(11),
  NOME          VARCHAR(50),
  CIDADE        VARCHAR(50),
  UF            VARCHAR(2)
);